version: "3"
services: 
    backup-server:
        container_name: backup-server
        restart: always
        image: backup-server:latest
        env_file: 
            - production.env
        ports: 
            - "4998:4998"
        deploy:
            resources:
                limits:
                    cpus: '0.03'
                    memory: 100m
                reservations:
                    cpus: '0.01'
                    memory: 60m